config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  resources :article_categories do
    resources :articles
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :article_category, :class_name => 'Article::Category'
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
            length: { minimum: 5 }
  validates :author_name, presence: true
end

app/models/article/category.rb
class Article::Category < ApplicationRecord
  has_many :articles, dependent: :destroy
  validates :name, presence: true
  validates :slug, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/article_categories_controller.rb
class ArticleCategoriesController < ApplicationController

  def index
    @category = Article::Category.all
  end

  def new
    raise ‘yyy’
    @category = Article::Category.new
  end

  def create
    raise ‘yyy’
    @category = Article::Category.new(category_params)
    #raise ‘yyy’
    if @category.save
      # binding.irb
      redirect_to @category
    else

      render 'new'
    end

  end

  def show
    @category = Article::Category.find(params[:id])
  end

  def edit
    raise ‘yyy’
    @category = Article::Category.find(params[:id])

  end

  def update
    raise ‘yyy’
    @category = Article::Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category = Article::Category.find(params[:id])
    @category.destroy

    redirect_to article_categories_path
  end

  private
  def category_params
    params.require(:article_category).permit(:name, :slug)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  #http_basic_authenticate_with name: "ann", password: "secret", except: [:index, :show]

    def index
      #@articles = Article.all
      @a = Article.ransack(params[:q])
      @articles = @a.result(distinct: true).page params[:page]

      #@articles = Article.all
    end

    def show
      @article = Article.find(params[:id])
    end

    def new
      @article = Article.new
    end

    def edit
      @article = Article.find(params[:id])
      binding.irb
    end

    def create
      @article = Article.new(article_params)
      raise ‘yyy’
      binding.irb
      if @article.save
        redirect_to @article
      else
        render 'new'
      end
    end

    def update
      @article = Article.find(params[:id])
      raise ‘yyy’
      if @article.update(article_params)
        redirect_to @article
      else
        render 'edit'
      end
    end

    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      raise ‘yyy’
      redirect_to articles_path
    end

    private
    def article_params
      params.require(:article).permit(:author_name, :state, :title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "ann", password: "secret", except: [:index, :show]

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    binding.irb
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_categories_helper.rb
module ArticleCategoriesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/article_categories/_form.html.slim
= simple_form_for @category do |f|

  .form-group
    = f.input :name
    = f.input :slug

  = f.button :submit, class: 'btn btn-primary'

app/views/article_categories/edit.html.slim
= render '/header'

.container
  h1
    | Edit category

  = render 'form'
  = link_to 'Back', article_categories_path

= render '/footer'

app/views/article_categories/index.html.slim
= render '/header'

.container
  h1
    | Listing Categories

  = link_to 'New category', new_article_category_path
  br

  table
    tr

      th
        | Name
      th
        | Slug
      th[colspan="3"]
    - @category.each do |category|
      tr
        td
          = category.name
        td
          = category.slug
        td
          = link_to 'Show', article_category_path(category)
        td
          = link_to 'Edit', edit_article_category_path(category)
        td
          = link_to 'Destroy', category, method: :delete, data: {confirm: 'Are you sure?'}

=render '/footer'

app/views/article_categories/new.html.slim
= render '/header'
.container
  h1
    | New category

  = render 'form'
  = link_to 'Back', article_categories_path

= render '/footer'

app/views/article_categories/show.html.slim
= render '/header'
.container
  h1
    | Category
  p
    strong
      | Name:
    = @category.name
  p
    strong
      | Slug:
    = @category.slug
  br
  = link_to 'Edit', edit_article_category_path(@category)
  |  |
  = link_to 'Back', article_categories_path

= render '/footer'

app/views/articles/_form.html.slim
= simple_form_for @article do |f|

  .form-group
    = f.input :author_name
    = f.input :state, collection: [['Draft', 'Draft'], ['Published', 'Published']]
    = f.input :title
    = f.text_area :text

  = f.button :submit, class: 'btn btn-primary'

app/views/articles/edit.html.slim
= render '/header'

.container
  h1
    | Edit article

  = render 'form'
  = link_to 'Back', articles_path

= render '/footer'

app/views/articles/index.html.slim
= render '/header'

.container
  h1
    | Listing Articles

  = link_to 'New article', new_article_path
  br

  = search_form_for @a do |f|
    .form-group
      = f.label :author_name_cont
      br
      = f.search_field :author_name_cont
    .form-group
      = f.label :title_start
      br
      = f.search_field :title_start
    .form-group
      = f.label :state_cont
      br
      = f.select(:state_cont, [['All', 'Draft || Published'], ['Draft', 'Draft'], ['Published', 'Published']])

    = f.submit
  br

  table
    tr

      th
        = sort_link(@a, :author_name)
      th
        = sort_link(@a, :state)
      th
        = sort_link(@a, :title)
      th
        = sort_link(@a, :text)
      th[colspan="3"]
    - @articles.each do |article|
      tr
        td
          = article.author_name
        td
          = article.state
        td
          = article.title
        td
          = article.text
        td
          = link_to 'Show', article_path(article)
        td
          = link_to 'Edit', edit_article_path(article)
        td
          = link_to 'Destroy', article, method: :delete, data: {confirm: 'Are you sure?'}

  = paginate @articles

= render '/footer'

app/views/articles/new.html.slim
| <!doctype html>
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"]
    link[rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"]
    title
      | New article
  body
    .container
      h1
        | New article

      = render 'form'
      = link_to 'Back', articles_path

    script[src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"]
    script[src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"]
    script[src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"]

app/views/articles/show.html.slim
= render '/header'
.container
  h1
    | Article
  p
    strong
      | Author name:
    = @article.author_name
  p
    strong
      | Title:
    = @article.title
  p
    strong
      | State:
    = @article.state
  p
    strong
      | Text:
    = @article.text

  h2
    | Comments
  h2
    | Add a comment:
  = link_to 'Edit', edit_article_path(@article)
  |  |
  = link_to 'Back', articles_path

= render '/footer'

app/views/comments/_comment.html.slim
p
  strong
    | Commenter:
  = comment.commenter
p
  strong
    | Comment:
  = comment.body
p
  = link_to 'Destroy Comment', [comment.article, comment],
  -               method: :delete,
  -               data: { confirm: 'Are you sure?' }

app/views/comments/_form.html.slim
= form_with(model: [ @article, @article.comments.build ]) do |form|
  p
    = form.label :commenter
    br
    = form.text_field :commenter
  p
    = form.label :body
    br
    = form.text_area :body
  p
    = form.submit

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Blog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/users/_form.html.slim
= form_with(model: user, local: true) do |form|
  - if user.errors.any?
    #error_explanation
      h2
        = pluralize(user.errors.count, "error")
        |  prohibited this user from being saved:
      ul
        - user.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :first_name
    = form.text_field :first_name, id: :user_first_name
  .field
    = form.label :last_name
    = form.text_field :last_name, id: :user_last_name
  .field
    = form.label :email
    = form.text_field :email, id: :user_email
  .actions
    = form.submit

app/views/users/edit.html.slim
h1
  | Editing User
= render 'form', user: @user
= link_to 'Show', @user
|  | 
= link_to 'Back', users_path

app/views/users/index.html.slim
p#notice
  = notice
h1
  | Users
table
  thead
    tr
      th
        | First name
      th
        | Last name
      th
        | Email
      th[colspan="3"]
  tbody
    - @users.each do |user|
      tr
        td
          = user.first_name
        td
          = user.last_name
        td
          = user.email
        td
          = link_to 'Show', user
        td
          = link_to 'Edit', edit_user_path(user)
        td
          = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1
  | New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice
  = notice
p
  strong
    | First name:
  = @user.first_name
p
  strong
    | Last name:
  = @user.last_name
p
  strong
    | Email:
  = @user.email
= link_to 'Edit', edit_user_path(@user)
|  | 
= link_to 'Back', users_path

app/views/welcome/index.html.slim
h1
  | Hello, Rails!
= link_to 'My Blog', controller: 'articles'